-- PUBLICZNE ZGŁOSZENIA BŁĘDÓW DO PYTAŃ JSM
-- Uruchom cały plik w Supabase -> SQL Editor.

create table if not exists public.jsm_question_reports (
  id bigint generated by default as identity primary key,
  question_id integer not null,
  message text not null,
  contact text,
  created_at timestamptz not null default now()
);

create index if not exists jsm_question_reports_question_id_idx
  on public.jsm_question_reports (question_id);

create index if not exists jsm_question_reports_created_at_idx
  on public.jsm_question_reports (created_at desc);

alter table public.jsm_question_reports enable row level security;

-- Użytkownik publiczny może tylko DODAĆ zgłoszenie.
-- Nie może odczytać zgłoszeń innych użytkowników.
drop policy if exists "JSM reports: public insert"
  on public.jsm_question_reports;

create policy "JSM reports: public insert"
  on public.jsm_question_reports
  for insert
  to anon, authenticated
  with check (
    question_id > 0
    and char_length(trim(message)) between 1 and 6000
    and (contact is null or char_length(contact) <= 180)
  );

grant insert on table public.jsm_question_reports
  to anon, authenticated;

grant usage, select on sequence public.jsm_question_reports_id_seq
  to anon, authenticated;

-- Brak polityki SELECT dla anon:
-- zwykły użytkownik nie może pobierać cudzych zgłoszeń.
-- Zgłoszenia są widoczne w Supabase Dashboard / SQL Editor.
