-- JSM: wspólna baza komentarzy do pytań
-- Uruchom CAŁY ten plik w Supabase -> SQL Editor.

create table if not exists public.jsm_question_reviews (
  id bigint generated by default as identity primary key,
  question_id integer not null,
  reviewer_name text not null,
  contact text,
  status text not null
    check (status in ('approved', 'needs_changes', 'delete')),
  coolness smallint not null
    check (coolness between 1 and 5),
  changes jsonb not null default '{}'::jsonb,
  change_details text,
  general_comment text,
  created_at timestamptz not null default now()
);

create index if not exists jsm_question_reviews_question_id_idx
  on public.jsm_question_reviews (question_id);

create index if not exists jsm_question_reviews_created_at_idx
  on public.jsm_question_reviews (created_at desc);

alter table public.jsm_question_reviews enable row level security;

drop policy if exists "JSM reviews: read" on public.jsm_question_reviews;
create policy "JSM reviews: read"
  on public.jsm_question_reviews
  for select
  to anon, authenticated
  using (true);

drop policy if exists "JSM reviews: insert" on public.jsm_question_reviews;
create policy "JSM reviews: insert"
  on public.jsm_question_reviews
  for insert
  to anon, authenticated
  with check (
    question_id > 0
    and char_length(trim(reviewer_name)) between 1 and 120
    and (contact is null or char_length(contact) <= 180)
    and status in ('approved', 'needs_changes', 'delete')
    and coolness between 1 and 5
    and (change_details is null or char_length(change_details) <= 4000)
    and (general_comment is null or char_length(general_comment) <= 6000)
  );

grant select, insert on table public.jsm_question_reviews
  to anon, authenticated;

grant usage, select on sequence public.jsm_question_reviews_id_seq
  to anon, authenticated;

-- Celowo nie ma polityk UPDATE ani DELETE:
-- komentarze mogą być dodawane i czytane, ale nie mogą być
-- zmieniane ani kasowane z przeglądarki.
