-- ================================================================
-- JSM PANEL ADMINA - WARIANT A
-- ================================================================
-- Uruchom CAŁY plik w Supabase -> SQL Editor.
--
-- Wariant A:
--   * istniejące pytania nadal są w questions.js,
--   * nowe/edytowane pytania robocze trafiają do jsm_questions,
--   * tylko status "published" trafia do eksportowanego questions.js,
--   * obrazki można wgrywać do publicznego bucketu Supabase Storage.
-- ================================================================


-- ---------- OPINIE DO PYTAŃ ----------

create table if not exists public.jsm_question_reviews (
  id bigint generated by default as identity primary key,
  question_id integer not null,
  reviewer_name text not null,
  contact text,
  status text not null
    check (status in ('approved', 'needs_changes', 'delete')),
  coolness smallint not null
    check (coolness between 1 and 5),
  changes jsonb not null default '{}'::jsonb,
  change_details text,
  general_comment text,
  created_at timestamptz not null default now()
);

create index if not exists jsm_question_reviews_question_id_idx
  on public.jsm_question_reviews (question_id);

create index if not exists jsm_question_reviews_created_at_idx
  on public.jsm_question_reviews (created_at desc);

alter table public.jsm_question_reviews enable row level security;

drop policy if exists "JSM reviews: read"
  on public.jsm_question_reviews;

create policy "JSM reviews: read"
  on public.jsm_question_reviews
  for select
  to anon, authenticated
  using (true);

drop policy if exists "JSM reviews: insert"
  on public.jsm_question_reviews;

create policy "JSM reviews: insert"
  on public.jsm_question_reviews
  for insert
  to anon, authenticated
  with check (
    question_id > 0
    and char_length(trim(reviewer_name)) between 1 and 120
    and (contact is null or char_length(contact) <= 180)
    and status in ('approved', 'needs_changes', 'delete')
    and coolness between 1 and 5
    and (change_details is null or char_length(change_details) <= 4000)
    and (general_comment is null or char_length(general_comment) <= 6000)
  );

grant select, insert on table public.jsm_question_reviews
  to anon, authenticated;

grant usage, select on sequence public.jsm_question_reviews_id_seq
  to anon, authenticated;


-- ---------- ROBOCZA BAZA NOWYCH PYTAŃ ----------

create table if not exists public.jsm_questions (
  id integer generated by default as identity (start with 211) primary key,

  author text,
  category text,
  difficulty text,

  question text,

  answer_a text,
  answer_b text,
  answer_c text,
  correct smallint
    check (correct is null or correct between 0 and 2),

  explanation text,
  image_url text,

  status text not null default 'draft'
    check (status in ('draft', 'review', 'published', 'archived')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jsm_questions_status_idx
  on public.jsm_questions (status);

create index if not exists jsm_questions_updated_at_idx
  on public.jsm_questions (updated_at desc);

create or replace function public.jsm_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists jsm_questions_set_updated_at
  on public.jsm_questions;

create trigger jsm_questions_set_updated_at
before update on public.jsm_questions
for each row execute function public.jsm_set_updated_at();

alter table public.jsm_questions enable row level security;

drop policy if exists "JSM questions: read"
  on public.jsm_questions;

create policy "JSM questions: read"
  on public.jsm_questions
  for select
  to anon, authenticated
  using (true);

drop policy if exists "JSM questions: insert"
  on public.jsm_questions;

create policy "JSM questions: insert"
  on public.jsm_questions
  for insert
  to anon, authenticated
  with check (
    status in ('draft', 'review', 'published', 'archived')
    and (author is null or char_length(author) <= 120)
    and (category is null or char_length(category) <= 120)
    and (difficulty is null or char_length(difficulty) <= 60)
    and (question is null or char_length(question) <= 5000)
    and (answer_a is null or char_length(answer_a) <= 2000)
    and (answer_b is null or char_length(answer_b) <= 2000)
    and (answer_c is null or char_length(answer_c) <= 2000)
    and (explanation is null or char_length(explanation) <= 6000)
    and (image_url is null or char_length(image_url) <= 2000)
  );

drop policy if exists "JSM questions: update"
  on public.jsm_questions;

create policy "JSM questions: update"
  on public.jsm_questions
  for update
  to anon, authenticated
  using (true)
  with check (
    status in ('draft', 'review', 'published', 'archived')
    and (author is null or char_length(author) <= 120)
    and (category is null or char_length(category) <= 120)
    and (difficulty is null or char_length(difficulty) <= 60)
    and (question is null or char_length(question) <= 5000)
    and (answer_a is null or char_length(answer_a) <= 2000)
    and (answer_b is null or char_length(answer_b) <= 2000)
    and (answer_c is null or char_length(answer_c) <= 2000)
    and (explanation is null or char_length(explanation) <= 6000)
    and (image_url is null or char_length(image_url) <= 2000)
  );

grant select, insert, update on table public.jsm_questions
  to anon, authenticated;

grant usage, select on sequence public.jsm_questions_id_seq
  to anon, authenticated;


-- ---------- OBRAZKI PYTAŃ ----------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'jsm-question-images',
  'jsm-question-images',
  true,
  5242880,
  array[
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/gif',
    'image/svg+xml'
  ]
)
on conflict (id) do update
set
  public = true,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "JSM question images: upload"
  on storage.objects;

create policy "JSM question images: upload"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'jsm-question-images');

-- Bucket jest publiczny, więc obrazy mogą być odczytywane przez zwykły URL.
-- Celowo nie dajemy z przeglądarki prawa DELETE do plików.


-- ================================================================
-- WAŻNE
-- ================================================================
-- Ta wersja nie ma jeszcze logowania adminów.
-- Klucz publishable/anon + RLS pozwala każdemu, kto zna panel/API,
-- czytać, dodawać i aktualizować roboczą bazę pytań.
-- Przed udostępnieniem panelu szerzej warto dodać Supabase Auth.
-- ================================================================
